title: Lecture Notes Collection
description: mathematics & physics lecture notes.
baseurl: ""      
url: "https://erisehe.github.io"

# Optional: add plugins if needed
plugins:
  - jekyll-feed

markdown: kramdown

